name: Deploy FastAPI to AWS Lambda with S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies into package dir
      run: |
        mkdir package
        pip install --upgrade pip
        pip install -r requirements.txt -t package/
        cp -r package/* .
        zip -r function.zip . -x '*.git*' '*.github*' '*.venv*' 'package/*'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload to S3
      run: aws s3 cp function.zip s3://${{ secrets.AWS_S3_BUCKET }}/function.zip

    - name: Deploy function from S3
      run: |
        aws lambda update-function-code \
          --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
          --s3-bucket ${{ secrets.AWS_S3_BUCKET }} \
          --s3-key function.zip
